# Angry

In [1]:
import numpy as np
import cv2
import csv
from glob import glob

#x = np.array([[20, 20],[20, 20]])
#x.shape[0]

# with open('test.txt', 'r') as file:
#     mystr = file.read()
# data = np.fromstring(mystr, np.uint8 ,sep=' ')


# num_shape = int(np.sqrt(data.shape[-1]))
# #num_shape

# data.shape = (num_shape,num_shape)
# # data

# cv2.imshow('im',data)
# cv2.waitKey(0)

## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh1.csv','a') as csvfile:
    
#     image_mask = cv2.imread("images/angry/*.jpg")
    img_mask ='images/angry/*.jpg'
    emotion = 0
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh1.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh1.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 
# cv2.imshow('im',test)
# cv2.waitKey(0)

[[143 144 144 ... 123 125 124]]
[[48 55 52 ... 46 41 35]]
[[255 255 255 ... 255 255 255]]
[[ 63  64  65 ... 163 147 143]]
[[255 255 255 ...  50  72  73]]
[[206 207 207 ... 191 188 185]]
[[232 232 236 ... 157 203 180]]
[[ 59  66  74 ... 121 118 100]]
[[179 182 184 ... 205 186 183]]
[[34 42 52 ... 77 63 51]]
[[58 59 65 ... 81 68 71]]
[[251 251 251 ... 179 243  92]]
[[68 76 80 ... 52 47 44]]
[[  0   0 251 ... 141   0   0]]
[[189 189 193 ... 112 142  78]]
[[54 57 67 ... 87 80 70]]
[[158 170 175 ...  70  69  67]]
[[123 130 111 ... 228 184 216]]
[[245 244 243 ...  30  35  34]]
[[192 161 159 ... 170 182 185]]


# disgust

In [2]:
## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh2.csv','a') as csvfile:

    img_mask ='images/disgust/*.jpg'
    emotion = 1
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh2.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh2.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 

[[255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[213 214 214 ... 206 206 206]]
[[13 14 16 ... 22 19 15]]
[[173 174 176 ... 137 142 135]]
[[250 250 250 ... 255 255 255]]
[[167 166 165 ... 129 132 127]]
[[196 197 196 ... 194 192 190]]
[[179 177 179 ... 179 179 179]]
[[255 255 254 ...  41  39 102]]
[[229 231 143 ... 128 130 168]]
[[210 210 210 ... 210 210 210]]
[[241 232 106 ...  17  30  27]]
[[ 87  89  90 ... 199 195 139]]
[[255 255 255 ...  50  50  50]]
[[164 166 185 ...  54  57  45]]
[[123 114 126 ... 103 118 166]]
[[241 241 241 ...  35  39  34]]
[[205 232 200 ... 198 211 217]]


# Fear

In [3]:
## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh3.csv','a') as csvfile:

    img_mask ='images/fear/*.jpg'
    emotion = 2
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh3.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh3.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 

[[ 80  83  84 ... 255 255 255]]
[[ 69  60 127 ...  15  17  14]]
[[11 11 12 ... 11  9  9]]
[[ 1  3  5 ...  5  7 14]]
[[  0   0   0 ... 255 255 255]]
[[0 0 0 ... 1 1 1]]
[[180 167 182 ...  42  38  48]]
[[155 149 147 ... 169 159 135]]
[[243 243 243 ...  28  35  34]]
[[181 195 192 ... 220 213 232]]


# Happy

In [4]:
import numpy as np
import cv2
import csv
from glob import glob

## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh4.csv','a') as csvfile:

    img_mask ='images/happy/*.jpg'
    emotion = 3
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh4.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh4.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 
# cv2.imshow('im',test)
# cv2.waitKey(0)

[[ 46  51  55 ... 102 140  70]]
[[132 124 125 ... 223 223 238]]
[[213 214 209 ...  36  33  41]]
[[170 208 152 ... 167 177 177]]


# Sad

In [5]:
import numpy as np
import cv2
import csv
from glob import glob

## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh5.csv','a') as csvfile:

    img_mask ='images/sad/*.jpg'
    emotion = 4
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh5.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh5.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 
# cv2.imshow('im',test)
# cv2.waitKey(0)

[[189 204 217 ... 196 200 199]]
[[136 140 144 ... 170 168 163]]
[[214 213 214 ...  11  13  29]]
[[160 166 167 ...  83  82 141]]
[[150 143 159 ... 119  99  81]]
[[ 77  75  78 ...  74 103  72]]
[[251 252 208 ... 232 252 255]]
[[57 62 66 ... 40 44 46]]
[[ 7  7  6 ... 25 22 22]]
[[255 255 255 ...  98 105 104]]
[[254 251 252 ... 198 217 255]]
[[248 248 248 ...  82  35  36]]
[[255 238 255 ... 210 203 183]]
[[255 255 255 ... 161 255 255]]
[[167 170 170 ...   2   5  11]]
[[157 172 164 ...  72  65  54]]
[[105 126 145 ...  81  95 123]]
[[250 249 249 ...  36  38  41]]


# Surprise

In [6]:
import numpy as np
import cv2
import csv
from glob import glob

## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh6.csv','a') as csvfile:

    img_mask ='images/happy/*.jpg'
    emotion = 5
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh6.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh6.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 
# cv2.imshow('im',test)
# cv2.waitKey(0)

[[ 46  51  55 ... 102 140  70]]
[[132 124 125 ... 223 223 238]]
[[213 214 209 ...  36  33  41]]
[[170 208 152 ... 167 177 177]]


# Neutral

In [7]:
import numpy as np
import cv2
import csv
from glob import glob

## angry:0, disgust:1, fear:2, happy:3, sad:4, surprise:5, neutral:6
with open('sh7.csv','a') as csvfile:

    img_mask ='images/neutral/*.jpg'
    emotion = 6
    img_names = glob(img_mask)
    for fn in img_names:
    # im_gray = cv2.imread('happy-man.jpg', cv2.IMREAD_GRAYSCALE)
        im_gray = cv2.imread(fn, cv2.IMREAD_GRAYSCALE)
    # #px = im_gray[48,48]
        resized_image = cv2.resize(im_gray, (48, 48))

        test = np.array(resized_image)
        test.shape = (1,2304)
        s = np.savetxt('sh7.txt', test, delimiter=' ', fmt='%i')   # X is an array
        pixels = str(test)
        print(pixels)
        a = open("sh7.txt", "r") 
        pixels = a.read()
    #         print(pixels)
        writer = csv.writer(csvfile)
        #     writer.writerow(['emotion', 'pixels', 'usage'])
            
        usage = 'Training'
        writer.writerow([emotion,pixels,usage]) 
# cv2.imshow('im',test)
# cv2.waitKey(0)

[[178 186 218 ... 250 250 249]]
[[125 119 115 ... 219 238 147]]
[[236 236 236 ... 236 236 236]]
[[130 206 172 ... 165 170 162]]


In [12]:
fout=open("out.csv","a")
# first file:
for line in open("sh1.csv"):
    fout.write(line)
# now the rest:    
for num in range(2,7):
    f = open("sh"+str(num)+".csv")
#     f.__next__() # skip the header
    for line in f:
         fout.write(line)
    f.close() # not really needed
fout.close()